### ISSUE TITLE
scimitar.bms - X360 forge files stopped working after script update

### ISSUE THREAD

**Issue by vladik4kides** [AnonBaiter/le_quickbms_script_compendium#1]
the title explains it all. After I've downloaded an update script from this repository, the script refused to extract stuff from my Data360 forge files, though the one from zenhax thread still works. 

![image](https://user-images.githubusercontent.com/55637550/65378865-5e49ac80-dcc7-11e9-907f-ce733bfb87d3.png)

**Comment by AnonBaiter** [comment]
oshit, i can't believe i haven't seen this coming...
in any case, feel free to post the file that's not working with this script from this repository and i'll see what i can do.

**Comment by vladik4kides** [comment]
[here it is](https://drive.google.com/open?id=0B2wXEaIcyofbbV96NS0xcUNKQTA)

**Comment by AnonBaiter** [comment]
OK, hold on.

**Comment by AnonBaiter** [comment]
turns out that this scimitar.bms that's currently available here works with all the .forge files you've provided for me. i'm using quickbms 0.10.0, but that's just on my end though. i don't know why it doesn't work on your end though.

anyway i've renamed this scimitar.bms script to scimitar_alt.bms to differentiate from the scimitar.bms script that's currently available on zenhax.

**Comment by vladik4kides** [comment]
thanks! turns out that the issue was in my quickbms, i've got the 0.10.0 one and it worked.
another question, where would you get that scimitar_compressed.bms script that's mentioned in scimitar.bms comments?

**Comment by AnonBaiter** [comment]
now that you've asked, here it is
[scimitar_compressed.bms](https://pastebin.com/kfn4JqaK)

i don't really recommend using it though as it is somewhat rougher if not outright unfinished thanks in no part for how the compressed chunks of a file were stored in Assassin's Creed. i'm talking about extracted files from Data360 forge archives.

**Comment by vladik4kides** [comment]
oh, okay. maybe that's why it didn't work on my forge files (nothing was output). guess we won't be able to get stuff from x360 version of just dance 3 for a while
